packages:
  - docs
  - playground
  - packages/*
  - examples/*

catalog:
  '@antfu/ni': ^27.0.1
  '@antfu/utils': ^9.3.0
  '@fonds/eslint-config': ^1.0.14
  '@types/lodash-es': ^4.17.12
  '@types/node': ^24.10.0
  bumpp: ^10.3.1
  eslint: ^9.39.1
  eslint-plugin-format: ^1.0.2
  lint-staged: ^16.2.6
  lodash-es: ^4.17.21
  simple-git-hooks: ^2.13.1
  tinyexec: ^1.0.2
  tsdown: ^0.16.0
  tsx: ^4.20.6
  typescript: ^5.9.3
  vite: ^7.2.1
  vitest: ^4.0.7
  vitest-package-exports: ^0.1.1
  yaml: ^2.8.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

shellEmulator: true
ignoreWorkspaceRootCheck: true
